apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: goapp
spec:
 type : LoadBalancer
 selector:
    app: goapp
 ports:
    - port: 80
      protocol: TCP
      targetPort: 8888